language: rust
notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGV0YSUzQXRoZXRhLmV1Lm9yZy8lMjFOVHNReUdldUllb1JPbEtZRHolM0F0aGV0YS5ldS5vcmc"
    on_success: change
    on_failure: always
    on_start: never
rust:
  - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
