language: rust
notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGV0YSUzQXRoZXRhLmV1Lm9yZy8lMjFOVHNReUdldUllb1JPbEtZRHolM0F0aGV0YS5ldS5vcmc"
    on_success: change
    on_failure: always
    on_start: never
services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
before_script:
  - psql -c 'CREATE DATABASE osm_test;' -U postgres
matrix:
  include:
    - rust: nightly
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
        - cargo run -p osms-db-setup -- -c osms-db-setup/config.toml.travis setup init
    - rust: stable
      cache: cargo
      script:
        - cargo build --verbose --all --exclude osms-web
        - cargo test --verbose --all --exclude osms-web
        - cargo run -p osms-db-setup -- -c osms-db-setup/config.toml.travis setup init
    - language: node_js
      node_js:
        - node
      script:
        - cd osms-web && npm install && npx gulp
  allow_failures:
    - rust: nightly
  fast_finish: true
