branches:
  only:
  - staging
  - trying
  - develop
  - master
language: rust
notifications:
  irc:
    channels:
      - "irc://theta.eu.org:6667/#osms"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: false
    nick: travisci
    password:
      secure: iCJAjwNB5au3SbmyL7bPSHpArlN/Nmh0SO2BjocmQrQrvGZcsD0TVQqfzP5dsMZWnsWYgTehVfH7TUJzpun84mTU5T0CnAZvKhuObEsmFJZhb8XMcSvHp8WKtZneyME4/xxW4PGX8WTdUGKffBNlpn680z1lUjanF5WhSHzvAgQYMjqgEbP73uJxNDDPqVosX1b549Tu4qIP/9NvXHXgqHLTwjraVWjCm1aJx+KjfGFPUusBDua4o3tc9hUgLQSEe+6ScbVjeiNIcaZJ8g2JWqWo4HjX1pZNuzkGJVyqkOLx+07tyiqFK0/wDkpMqyzMxVYaNj417/FiRDiGCCsUpOkwLt0o9MUHP9l26uK7+f1TA+5oDmi7t8SW23+ZMSrwvKU/QFGvAk97ecyoBe6teG/8GdMUW23RlgSrOJJQYikZUrGI2nIhyuzJMoTovknFtg6pUL4ZjPMr0yWLIYK8Kvu6U946GodF79w86/PE6DZiGMayIjRdz6i4/3oePt+dePB0wDgjKvl6xj03WdijlCWsPt5zETkF6maIenBLzNJZzMaornZVGlJKTzJHI9LP5NTzSk+8IGAZ0BpYyNktBOrVcLO+B9dTG1pia8rictWmEcKEzcI8DOkN0T1Ibz1GFa5v2qXjdeK05I2BMZzW6DphTQswb46kwKmkmIdG//M=
services:
- postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
- psql -c 'CREATE DATABASE osm_test;' -U postgres
matrix:
  include:
  - rust: nightly
    script:
    - cargo build --verbose --all
    - cargo test --verbose --all
    - source osms-db-setup/setup-travis.sh && cargo run -p osms-db-setup -- setup
      init
  - rust: stable
    cache:
      cargo: true
      timeout: 1000
    script:
    - cargo build --verbose --all
    - cargo test --verbose --all
    - source osms-db-setup/setup-travis.sh && cargo run -p osms-db-setup -- setup
      init
  - language: node_js
    node_js:
    - node
    script:
    - cd osms-web && npm install && npx gulp
  allow_failures:
  - rust: nightly
  fast_finish: true
