language: rust
notifications:
  irc:
    channels:
      - "chat.freenode.net#osm-signal"
    on_success: change
    on_failure: always
    use_notice: true
services:
  - postgresql
cache:
  timeout: 1000
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
before_script:
  - psql -c 'CREATE DATABASE osm_test;' -U postgres
matrix:
  include:
    - rust: nightly
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
        - source osms-db-setup/setup-travis.sh && cargo run -p osms-db-setup -- setup init
    - rust: stable
      cache: cargo
      script:
        - cargo build --verbose --all --exclude osms-web
        - cargo test --verbose --all --exclude osms-web
        - source osms-db-setup/setup-travis.sh && cargo run -p osms-db-setup -- setup init
    - language: node_js
      node_js:
        - node
      script:
        - cd osms-web && npm install && npx gulp
  allow_failures:
    - rust: nightly
  fast_finish: true
