branches:
  only:
    - staging
    - trying
    - develop
    - master
language: rust
  webhooks: https://ingest.devmode.cloud/hooks/travisci?channel=%23osm-signal
services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
before_script:
  - psql -c 'CREATE DATABASE osm_test;' -U postgres
matrix:
  include:
    - rust: nightly
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
        - source osms-db-setup/setup-travis.sh && cargo run -p osms-db-setup -- setup init
    - rust: stable
      cache:
        cargo: true
        timeout: 1000
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
        - source osms-db-setup/setup-travis.sh && cargo run -p osms-db-setup -- setup init
    - language: node_js
      node_js:
        - node
      script:
        - cd osms-web && npm install && npx gulp
  allow_failures:
    - rust: nightly
  fast_finish: true
