[workspace]
members = ["./ntrod-types", "./atoc-msn", "./darwin-types", "./tspl-sqlite", "./tspl-fahrplan", "./tspl-util", "./tspl-zugfuhrer", "./tspl-nrod"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
