[workspace]
members = ["./osms-db", "./national-rail-departures", "./osms-nrod", "./ntrod-types", "./osms-db-setup", "./osms-web", "./atoc-msn", "./osms-darwin"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
