[workspace]
members = ["./osms-db", "./osms-nrod", "./ntrod-types", "./osms-db-setup", "./osms-web", "./atoc-msn", "./osms-darwin", "./darwin-types"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
