steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/trainsplorer/tspl-builder:latest || exit 0

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pkgs=("tspl-builder" "tspl-compiled" "tspl-base" "tspl-fahrplan" "tspl-zugfuhrer" "tspl-nrod" "tspl-fahrplan-updater"); for thing in ${pkgs[@]}; do docker build -f "docker/$thing" -t "$thing" --cache-from gcr.io/trainsplorer/tspl-builder:latest .; done
  timeout: 4000s

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pkgs=("tspl-builder" "tspl-fahrplan" "tspl-zugfuhrer" "tspl-nrod" "tspl-fahrplan-updater"); for thing in ${pkgs[@]}; do docker tag "$thing" "gcr.io/trainsplorer/$thing:latest"; docker tag "$thing" "gcr.io/trainsplorer/$thing:$COMMIT_SHA"; docker push "gcr.io/trainsplorer/$thing"; done

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', 'tspl-cluster-ii']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'
  - 'CLOUDSDK_CONTAINER_CLUSTER=tspl-cluster-ii'

- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pkgs=("tspl-fahrplan" "tspl-zugfuhrer"); for thing in ${pkgs[@]}; do kubectl -n tspl set image statefulset "$thing" "$thing=gcr.io/trainsplorer/$thing:$COMMIT_SHA"; done

- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pkgs=("tspl-nrod"); for thing in ${pkgs[@]}; do kubectl -n tspl set image deployment "$thing" "$thing=gcr.io/trainsplorer/$thing:$COMMIT_SHA"; done

- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    kubectl -n tspl set image deployment "tspl-darwin" "tspl-nrod=gcr.io/trainsplorer/tspl-nrod:$COMMIT_SHA"

- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    kubectl -n tspl set image cronjob "tspl-fahrplan-updater" "tspl-fahrplan-updater=gcr.io/trainsplorer/tspl-fahrplan-updater:$COMMIT_SHA"




images:
- 'gcr.io/trainsplorer/tspl-builder:latest'
- 'gcr.io/trainsplorer/tspl-fahrplan:$COMMIT_SHA'
- 'gcr.io/trainsplorer/tspl-zugfuhrer:$COMMIT_SHA'
- 'gcr.io/trainsplorer/tspl-nrod:$COMMIT_SHA'
timeout: 5000s

