[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
edition = "2018"
name = "tspl-util"
version = "0.1.0"

[dependencies]
config = "0.9"
failure = "0.1"
failure_derive = "0.1"
fern = "0.5"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
reqwest = "0.9"
