apiVersion: batch/v1
kind: Job
metadata:
  name: osms-db-setup-nrod
spec:
  template:
    spec:
      containers:
      - name: osms-db-setup
        image: gcr.io/trainsplorer/osms-db-setup:latest
        command:
        - bash
        - "-c"
        - |
          mkdir /tspl/init && curl "https://theta.eu.org/stash/nrod-init.tar.gz" | tar xz -C "/tspl/init" && /tspl/osms-db-setup setup nrod --corpus /tspl/init/corpus.json.gz --msn /tspl/init/msn.msn --naptan /tspl/init/naptan.csv 
        env:
        - name: RUST_BACKTRACE
          value: "full"
        - name: OSMS_REQUIRE_TLS
          value: "false"
        - name: OSMS_N_THREADS
          value: "1"
        - name: OSMS_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: database
        - name: OSMS_USERNAME
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: nrod_username
        - name: OSMS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: nrod_password
      restartPolicy: Never
  backoffLimit: 4

