apiVersion: apps/v1
kind: Deployment
metadata:
  name: osms-web-deployment
  labels:
    app: osms-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osms-web
  template:
    metadata:
      labels:
        app: osms-web
    spec:
      containers:
      - name: osms-web
        image: gcr.io/trainsplorer/osms-web:latest
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"
        env:
        - name: RUST_BACKTRACE
          value: "full"
        - name: OSMS_LISTEN
          value: "0.0.0.0:8080"
        - name: OSMS_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: database

