apiVersion: apps/v1
kind: Deployment
metadata:
  name: osms-nrod-deployment
  labels:
    app: osms-nrod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: osms-nrod
  template:
    metadata:
      labels:
        app: osms-nrod
    spec:
      containers:
      - name: osms-nrod
        image: gcr.io/trainsplorer/osms-nrod:latest
        env:
        - name: RUST_BACKTRACE
          value: "full"
        - name: OSMS_N_THREADS
          value: "12"
        - name: OSMS_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: database
        - name: OSMS_USERNAME
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: nrod_username
        - name: OSMS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: nrod_password
        - name: OSMS_DARWIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: darwin_username
        - name: OSMS_DARWIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: darwin_password
        - name: OSMS_DARWIN_QUEUE_NAME
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: darwin_queue_name
        - name: OSMS_DARWIN_URL
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: darwin_url
        - name: OSMS_DARWIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: darwin_password



