apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: osms-db-sched-update
spec:
  schedule: "* 6 * * *" 
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: osms-db-setup
            image: gcr.io/trainsplorer/osms-db-setup:latest
            command: ["/tspl/osms-db-setup", "schedule", "update"]
            env:
            - name: RUST_BACKTRACE
              value: "full"
            - name: OSMS_REQUIRE_TLS
              value: "false"
            - name: OSMS_N_THREADS
              value: "4"
            - name: OSMS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: tspl-secrets
                  key: database
            - name: OSMS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tspl-secrets
                  key: nrod_username
            - name: OSMS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tspl-secrets
                  key: nrod_password
          restartPolicy: Never

