apiVersion: v1
kind: Service
metadata:
  name: tspl-fahrplan
  namespace: tspl
  labels:
    app: tspl-fahrplan
spec:
  ports:
  - port: 80
    name: rpc
  selector:
    app: tspl-fahrplan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tspl-fahrplan
  namespace: tspl
  labels:
    app: tspl-fahrplan
spec:
  selector:
    matchLabels:
      app: tspl-fahrplan
  replicas: 2
  template:
    metadata:
      namespace: tspl
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: tspl-fahrplan
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: tspl-fahrplan
        image: gcr.io/trainsplorer/tspl-fahrplan:latest
        ports:
        - containerPort: 80
          name: rpc
        volumeMounts:
          - name: service-account
            mountPath: /tspl/updater_service_account.json
            subPath: updater_service_account.json
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        env:
        - name: RUST_BACKTRACE
          value: "full"
        - name: TSPL_BUCKET_NAME
          value: "trainsplorer-fahrplan"
        - name: TSPL_SERVICE_ACCOUNT_KEY_PATH
          value: "/tspl/updater_service_account.json"
        - name: TSPL_LISTEN_URL
          value: "0.0.0.0:80"
        - name: TSPL_USERNAME
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: nrod_username
        - name: TSPL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: nrod_password
      volumes:
        - name: service-account
          secret:
            secretName: tspl-secrets
