apiVersion: batch/v1
kind: Job
metadata:
  name: tspl-fahrplan-init
  namespace: tspl
spec:
  template:
    metadata:
      namespace: tspl
    spec:
      containers:
      - name: tspl-fahrplan-init
        image: byrnedo/alpine-curl:latest
        args: ["-X", "POST", "http://tspl-fahrplan/update/init"]
      restartPolicy: Never
  backoffLimit: 4

