apiVersion: v1
kind: Service
metadata:
  name: tspl-fahrplan
  labels:
    app: tspl-fahrplan
spec:
  ports:
  - port: 7000
    name: rpc
  clusterIP: None
  selector:
    app: tspl-fahrplan
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tspl-fahrplan
spec:
  selector:
    matchLabels:
      app: tspl-fahrplan
  replicas: 1
  serviceName: tspl-fahrplan
  template:
    metadata:
      labels:
        app: tspl-fahrplan
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: tspl-fahrplan
        image: gcr.io/trainsplorer/tspl-fahrplan:latest
        ports:
        - containerPort: 7000
          name: rpc
        volumeMounts:
        - name: fahrplan-data
          mountPath: /data/
        env:
        - name: RUST_BACKTRACE
          value: "full"
        - name: TSPL_DATABASE_PATH
          value: "/data/fahrplan.sqlite"
        - name: TSPL_LISTEN_URL
          value: "tcp://0.0.0.0:7000"
        - name: TSPL_USERNAME
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: nrod_username
        - name: TSPL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tspl-secrets
              key: nrod_password
  volumeClaimTemplates:
  - metadata:
      name: fahrplan-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
