[package]
name = "tspl-verknupfen"
version = "0.1.0"
authors = ["eta <hi@theta.eu.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
