[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "osms-db-setup"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
fern = "0.4.2"
log = "0.3.8"
postgres = "0.15"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

[dependencies.osms-db]
path = "../osms-db"
