[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "osms-db-setup"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
fern = "0.4.2"
flate2 = "0.2.20"
log = "0.3.8"
r2d2 = "0.7.4"
r2d2_postgres = "0.13.0"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

[dependencies.osms-db]
path = "../osms-db"
