[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "darwin-types"
version = "0.2.0"
edition = "2018"

[dependencies]
chrono = "0.4"
failure = "0.1"
failure_derive = "0.1"
derive_builder = "0.7"
xml-rs = "0.8"
