[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "osms-db"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
log = "0.3.8"
postgis = "0.4.0"
postgres = "0.14"

[dev-dependencies]
clap = "2.26.0"
env_logger = "0.4"
