[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "osms-db"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
chrono-tz = "0.4.1"
error-chain = "0.10.0"
log = "0.3.8"
postgres-derive = "0.3.1"
serde_json = "1.0.2"

[dependencies.ntrod-types]
features = ["postgres-traits"]
path = "../ntrod-types"

[dependencies.postgis]
git = "https://github.com/andelf/rust-postgis"

[dependencies.postgres]
features = ["with-chrono"]
version = "0.15"

[dev-dependencies]
clap = "2.26.0"
env_logger = "0.4"
