[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "osms-db"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
error-chain = "0.10.0"
fallible-iterator = "0.1"
log = "0.3.8"
postgres-derive = "0.3.1"
r2d2 = "0.7.4"
r2d2_postgres = "0.13.0"
serde_json = "1.0.2"
ordered-float = "0.5"

[dependencies.geo]
git = "https://github.com/eeeeeta/rust-geo"

[dependencies.ntrod-types]
features = ["postgres-traits"]
path = "../ntrod-types"

[dependencies.postgis]
version = "0.5"

[dependencies.postgres]
features = ["with-chrono"]
version = "0.15"

[dev-dependencies]
clap = "2.26.0"
env_logger = "0.4"
