[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "osms-web"
version = "0.1.0"

[dependencies]
postgres = "0.15"
r2d2 = "0.7.4"
r2d2_postgres = "0.13.0"
rocket = "0.3.2"
rocket_codegen = "0.3.2"

[dependencies.osms-db]
path = "../osms-db"

[dependencies.rocket_contrib]
features = ["json", "handlebars_templates"]
version = "0.3.2"
