apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  namespace: tspl
  name: tspl-zugfuhrer.tspl.svc.cluster.local 
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /
    name: version check
  - condition:
      method: GET
      pathRegex: /train-movements/through/[^/]*/at/[^/]*/within-secs/[^/]*
    name: get train movements through a given point
  - condition:
      method: GET
      pathRegex: /train-movements/through/[^/]*/and/[^/]*/at/[^/]*/within-secs/[^/]*
    name: get connecting train movements through two given points
  - condition:
      method: GET
      pathRegex: /trains/by-trust-id/[^/]*/[^/]*
    name: find a train by TRUST ID and date
    isRetryable: true
  - condition:
      method: GET
      pathRegex: /trains/by-darwin-rid/[^/]*
    name: find a train by Darwin RID
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /trains/[^/]*/trust-id/[^/]*
    name: associate a train with a TRUST ID
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /trains/activate
    name: activate a train
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /trains/activate-fuzzy
    name: activate a train (Darwin)
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /trains/[^/]*/terminate
    name: mark a train as terminated
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /trains/[^/]*/cancel
    name: mark a train as cancelled
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /trains/[^/]*/trust-movement
    name: register a TRUST movement for a train
  - condition:
      method: POST
      pathRegex: /trains/[^/]*/darwin/update
    name: register a Darwin movement for a train
