[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "osms-nrod"
version = "0.1.0"

[dependencies]
env_logger = "0.4.3"
serde_json = "1.0.2"
ntrod-types = { path = "../ntrod-types" }
osms-db = { path = "../osms-db" }
log = "0.3.8"
postgres = "0.15"
clap = "2.26.0"

[dependencies.stomp]
git = "https://github.com/zslayton/stomp-rs"
branch = "use-mai"
