[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "osms-nrod"
version = "0.1.0"

[dependencies]
env_logger = "0.4.3"
serde_json = "1.0.2"
ntrod-types = { path = "../ntrod-types" }
[dependencies.stomp]
path = "../../stomp-rs"
