[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
name = "osms-nrod"
version = "0.1.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.4.3"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"

[dependencies.stomp]
path = "../../stomp-rs"
