[package]
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]
edition = "2018"
name = "tspl-fahrplan"
version = "0.1.0"

[dependencies]
bitflags = "1.0.4"
chrono = "0.4"
failure = "0.1"
failure_derive = "0.1"
log = "0.4"
uuid = "0.7"

[dependencies.tspl-sqlite]
path = "../tspl-sqlite"

[dependencies.tspl-util]
path = "../tspl-util"
